version: '3'
services:
  app:
    image: jc21/nginx-proxy-manager:2.9.18
    container_name: proxy-mgr-web
    restart: always
    ports:
      - '81:81'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - $PWD/data:/data
      - $PWD/letsencrypt:/etc/letsencrypt
  db:
    image: jc21/mariadb-aria:10.4.15
    container_name: proxy-mgr-db
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - $PWD/mysql:/var/lib/mysql